basket/urls.py
from django.urls import path

from basket.views import BasketDetailView, BasketManagementAjaxView

urlpatterns = [
    path("manage/", BasketManagementAjaxView.as_view(), name="basket_management_ajax"),
    path('', BasketDetailView.as_view(), name="basket"),
]

listing/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'listing'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<slug:slug>', views.product_list, name='product_list'),
    path('search', views.search, name='search'),
    url(r'^filter', views.filter, name='filter'),
]

marketplace/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve

from comment.views import BasicCommandCreateView
# from core.views import HomePageView
from listing.views import IndexView
from product.views import ProductDetailsView

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('product/<slug:slug>/comments/add/', BasicCommandCreateView.as_view(), name="add_comment"),
    path('product/<slug:slug>/', ProductDetailsView.as_view(), name="product_details"),
    path('basket/', include('basket.urls')),
    path('shipment/', include('shipment.urls')),
    path('listing/', include('listing.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', IndexView.as_view(), name="homepage"),
)

if settings.DEBUG:
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns += [
            path('__debug__/', include(debug_toolbar.urls)),
        ]
    urlpatterns += [path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT})]

listing/models.py
from django.db import models

# Create your models here.

listing/views.py
from django.shortcuts import render
from django.views import generic
from product.models import Product
import re

class IndexView(generic.ListView):
    template_name = 'listing/index.html'
    context_object_name = 'products'

    def get_queryset(self):
        sample_entities = Product.objects.order_by('?')[:5]
        return sample_entities

#List products
def product_list(request, slug):
    if slug[:6] == 'search':
        return search(request)
        
    products = Product.objects.filter(category__slug = slug)
    context = {'products': products, "category": slug, "show_filter": True}
    return render(request, 'listing/product_list.html', context)


def is_valid_queryparam(param):
    return param != '' and param is not None

def filter(request):
    slug = request.GET["category"]
    products = Product.objects.filter(
        category__slug=slug)
    
    min_price = request.GET.get('min-price')
    if is_valid_queryparam(min_price):
        products = products.filter(price__gte  =  min_price)
        
    max_price = request.GET.get('max-price')
    if is_valid_queryparam(max_price):
        products = products.filter(price__lte  =  max_price)
    
    
    price_and_category_filtered = products
    
    brand_vodafone = request.GET.get('Vodafone')
    brand_samsung = request.GET.get('Samsung')
    brand_iphone = request.GET.get('Iphone')
    brand_huawei = request.GET.get('Huawei')
    brand_xiaomi = request.GET.get('Xiaomi')
    
    
    all_products = []
    flag = True
    if brand_vodafone == 'on':
        products = price_and_category_filtered.filter(description__icontains="Vodafone") | price_and_category_filtered.filter(description__icontains="Vodafone")
        all_products += products
        flag = False
    if brand_iphone == 'on':
        products = price_and_category_filtered.filter(description__icontains="Iphone") | price_and_category_filtered.filter(name__icontains="Iphone")
        all_products += products
        flag = False
    if brand_samsung == 'on':
        products = price_and_category_filtered.filter(description__icontains="Samsung") | price_and_category_filtered.filter(name__icontains="Samsung")
        all_products += products
        flag = False
    if brand_xiaomi == 'on':
        products = price_and_category_filtered.filter(description__icontains="Xiaomi") | price_and_category_filtered.filter(name__icontains="Xiaomi")
        all_products += products
        flag = False
    if brand_huawei == 'on':
        products = price_and_category_filtered.filter(description__icontains="Huawei") | price_and_category_filtered.filter(name__icontains="Huawei")
        all_products += products
        flag = False
    
    
    context = {'products': price_and_category_filtered if flag else all_products, "category": slug, "show_filter": False}
    return render(request, 'listing/product_list.html', context)

def search(request):
    searchText = request.GET['searchText']
    allProducts = Product.objects.all()
    foundProducts = []
    for product in allProducts:
         if(regexSearch(searchText.lower(), product.name.lower())):
            foundProducts.append(product)
         elif(regexSearch(searchText.lower(), product.description.lower())):
            foundProducts.append(product)
    
    context = {'products': foundProducts}
    return render(request, 'listing/product_list.html', context)


#Search utility function
def regexSearch(searchText, sentence):
    for x in range(0, len(searchText)):
        sText = searchText[:x] + '.' + searchText[x+1:]
        result = re.search(sText, sentence)
        if result is not None:
            return True
        
        
    return False

listing/templates/listing/index.html
{% extends "base.html" %} {% load static %} {% block title %}Index{% endblock %} {% block extraHead %}
{% load i18n static humanize thumbnail %}

<script type="text/javascript" src="{% static " js/jquery.min.js " %}"></script>
<script type="text/javascript" src="{% static " bootstrap/js/bootstrap.min.js " %}"></script>
<link rel='stylesheet' href='https://cdn.jsdelivr.net/jquery.slick/1.6.0/slick.css'>
<link rel="stylesheet" href="{% static 'listing/banner.css' %}">
<link rel="stylesheet" href="{% static 'listing/index-style.css' %}">{% endblock %} {% block content %}
<div  style="margin-bottom: 60px; margin-top: 60px;" class="page-header">
    <form class="example" action="{% url 'listing:search' %}">
        <input type="text" placeholder="Ara..." name="searchText">
        <button type="submit">
            <i class="fa fa-search"></i>
        </button>
    </form>
</div>



<div class="card-carousel">
    {% for product in products %}
    <div class="my-card card" style="width: 16rem; height: 20rem; background: white; border-color: #E60000">

        {% thumbnail product.main_image.image "250x250" crop="center" as im %}
            <img  style="margin-top: 5%; margin-bottom: 5%; margin-left: 25%; height: 8rem; width: 8rem; " src={{im.url}}   alt="{{ image.title }}"/>
        {% endthumbnail %}

        <div class="card-body">
            <h5 style="font-size: small;" class="card-title vodafone-red-text text-center">{{product.name}}</h5>
            <h5 style="font-size: large;" class="card-title vodafone-grey-text text-center">₺ {{product.price}}</h5>
            <a style="margin-top: 2%;" method="get"  href="/product/{{ product.slug}}/"  class="btn btn-lg text-center text-white vodafone-red-back">İncele</a>
        </div>
    </div>
    {% endfor %}
</div>
<div style="padding-bottom: 250px"></div>





{% endblock %} {% block extraJS %}
<script>
    $num = $('.my-card').length;
    $even = $num / 2;
    $odd = ($num + 1) / 2;

    if ($num % 2 == 0) {
        $('.my-card:nth-child(' + $even + ')').addClass('active');
        $('.my-card:nth-child(' + $even + ')').prev().addClass('prev');
        $('.my-card:nth-child(' + $even + ')').next().addClass('next');
    } else {
        $('.my-card:nth-child(' + $odd + ')').addClass('active');
        $('.my-card:nth-child(' + $odd + ')').prev().addClass('prev');
        $('.my-card:nth-child(' + $odd + ')').next().addClass('next');
    }

    $('.my-card').click(function() {
        $slide = $('.active').width();
        console.log($('.active').position().left);

        if ($(this).hasClass('next')) {
            $('.card-carousel').stop(false, true).animate({
                left: '-=' + $slide
            });
        } else if ($(this).hasClass('prev')) {
            $('.card-carousel').stop(false, true).animate({
                left: '+=' + $slide
            });
        }

        $(this).removeClass('prev next');
        $(this).siblings().removeClass('prev active next');

        $(this).addClass('active');
        $(this).prev().addClass('prev');
        $(this).next().addClass('next');
    });


    // Keyboard nav
    $('html body').keydown(function(e) {
        if (e.keyCode == 37) { // left
            $('.active').prev().trigger('click');
        } else if (e.keyCode == 39) { // right
            $('.active').next().trigger('click');
        }
    });
</script>
{% endblock %}

listing/templates/listing/product_list.html
{% extends "base.html" %} {% load static %} {% block title %}Listing{% endblock %} {% block content %} {% load i18n static humanize thumbnail %}
<link rel="stylesheet" href="{% static 'listing/index-style.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<section class="listing-section">
    <button class="filter-button" onclick="filterFunction()"><i class="fa fa-filter"></i></button>

    <form method="GET" id="filter" action="{% url 'listing:filter' %}/ " class="Menu">

        <div class="section">
            <div class="section-header">
                <span class="section-header-name" dir="auto">Kategoriye göre</span>
            </div>
            <ul class="section-list">
                {% for category in categories %}
                <li>
                    <a href="{% url 'listing:product_list' category.slug %}" method="get" class="Category-item" data-menu-id="2" data-ref-tag="nav_em_1_1_1_2">
                        <div>{{category.name }}</div><i class="nav-sprite hmenu-arrow-next"></i>
                    </a>
                </li>
                {% endfor %}
            </ul>
        </div>
        <div class="section">
            <div class="section-header">
                <span class="section-header-name" dir="auto">Marka</span>
            </div>
            <ul class="section-list">
                <li><label for="section-name"><input type="checkbox" id="Vodafone" name="Vodafone">Vodafone</label></li>
                <li><label for="section-name"><input type="checkbox" id="Samsung" name="Samsung">Samsung</label></li>
                <li><label for="section-name"><input type="checkbox" id="Iphone" name="Iphone">Iphone</label></li>
                <li><label for="section-name"><input type="checkbox" id="Xiaomi" name="Xiaomi">Xiaomi</label></li>
                <li><label for="section-name"><input type="checkbox" id="Huawei" name="Huawei">Huawei</label></li>
            </ul>
        </div>
        <div class="section">
            <div class="section-header">
                <span class="section-header-name" dir="auto">Fiyat</span>
            </div>
            <ul class="section-list">
                <li class="section-name">
                    <div class="input-group-append price-range">
                        <input type="text" class="price-box" id="min-price" maxlength="9" placeholder="Min ₺" name="min-price"><br>
                        <input type="text" class="price-box" id="max-price" name="max-price" maxlength="9" placeholder="Maks ₺" style="padding-left: 9px;"><br><br>
                    </div>
                    <input type="hidden" id="category" name="category" value={{category}}>
                </li>
            </ul>
        </div>
        <button type="submit" class="btn-submit">Ürünlere Git</button>
    </form>




    <div style="margin-left: 20%; margin-right: 5%;">
        <table class="table">
            {% for product in products %}
            <tr>

                <div class="card border-secondary rounded " style="margin-top: 2%; box-shadow: 5px 10px #4A4D4E;">
                    <div class="row no-gutters">
                        <div class="col-3 text-center">
                            {% thumbnail product.main_image.image "350x350" crop="center" as im %}
                            <a href="{{ product.main_image.image.url }}" data-lightbox="roadtrip" data-title="{{ image.title }}">
                                <img src={{im.url}} style="margin-top: 2%; margin-bottom: 2%; margin-left: 2%" alt="{{ image.title }}" />
                            </a>
                            {% endthumbnail %}

                        </div>

                        <div class="col-9">
                            <div class="card-block px-5" style="margin-top: 1rem; margin-left: 3%">
                                <h4 class="card-title vodafone-red-text">{{product.name}}</h4>

                                <h4 class="card-title vodafone-grey-text">₺ {{product.price}}</h4>
                                <h4>
                                    <svg class="bi bi-star-fill text-warning" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                      <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                    </svg> {% if product.average_rating %}{{ product.average_rating }}/100{% else %} {% trans "N/A" %}{% endif %}
                                </h4>
                                <p class="card-text vodafone-grey-text">{{product.description}}</p>
                                <a method="get" href="/product/{{ product.slug}}/" style="position:absolute; bottom: 3%; " class="btn btn-lg text-center text-white vodafone-red-back t">İncele</a>
                            </div>
                        </div>
                    </div>
                </div>
            </tr>
            {% endfor %}
        </table>

    </div>

</section>


{% block extraJS %}
<script type="text/javascript">
    var hashParams = $(location).attr("href").split('?')[1].split('&');
    for (var i = 0; i < hashParams.length; i++) {
        var p = hashParams[i].split('=');
        if (decodeURIComponent(p[1]) == "on") {
            document.getElementById(p[0]).checked = 'checked'
        } else {
            document.getElementById(p[0]).value = decodeURIComponent(p[1]);
        }
    }

    function filterFunction() {
        if (document.getElementById("filter").style.width == "250px") {
            document.getElementById("filter").style.transition = "0.5s";
            document.getElementById("filter").style.width = "0px";
        } else {
            document.getElementById("filter").style.transition = "0.5s";
            document.getElementById("filter").style.width = "250px";
        }
    }
</script>
{% endblock %} {% endblock %}